# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout:
      - run: npm i
      - save_cache:
          key: node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
          paths:
            - ~/.npm
      - run: npm run lint
  test:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout:
      - restore_cache:
         keys:
           - node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
      - run: npm i
      - run: mpm run test
  analyze:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout:
      - restore_cache:
         keys:
           - node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
      - run: npm audit
workflows:
  my_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
